### PR TITLE
allow symfony/* 4

### PR DESCRIPTION
**Pull request by kornrunner**
Allow Symfony 4

### CODE REVIEW

**Comment by sokil** [comment]
Event dispatcher in sokil/php-mongo set to < 4.0 so you newer get >=4.0 here. You can update version there and remove requirement from dispatcher here due to duplication of requirement.

**Comment by kornrunner** [comment]
Updated PR per your comments

**Comment by kornrunner** [comment]
Thank you! Could this be tagged as a minor, please?

**Comment by sokil** [comment]
already) thanks fot contribution

**Pull request merged**
